apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arena-web-data
  namespace: incident-arena-09
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 100Mi
