apiVersion: apps/v1
kind: Deployment
metadata:
  name: arena-web
  namespace: incident-arena-09
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arena-web
  template:
    metadata:
      labels:
        app: arena-web
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - name: http
              containerPort: 80
          env:
            - name: APP_MODE
              valueFrom:
                secretKeyRef:
                  name: arena-web-secret
                  key: app_mode
          volumeMounts:
            - name: app-data
              mountPath: /var/lib/arena
      volumes:
        - name: app-data
          persistentVolumeClaim:
            claimName: arena-web-data
