apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: arena-store
  namespace: incident-arena-04
spec:
  serviceName: arena-store
  replicas: 1
  selector:
    matchLabels:
      app: arena-store
  template:
    metadata:
      labels:
        app: arena-store
        component: stateful-web
    spec:
      initContainers:
        - name: prepare-content
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              set -eu
              if [ ! -f /data/created-at.txt ]; then
                date -u +%Y-%m-%dT%H:%M:%SZ > /data/created-at.txt
              fi
              cp /config/index.html /data/index.html
              printf 'created_at=%s\n' "$(cat /data/created-at.txt)" >> /data/index.html
              printf 'pod=%s\n' "$(hostname)" >> /data/index.html
          volumeMounts:
            - name: content
              mountPath: /config
              readOnly: true
            - name: data
              mountPath: /data
      containers:
        - name: web
          image: nginx:1.27-alpine
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 2
            periodSeconds: 3
          resources:
            requests:
              cpu: 20m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 96Mi
          volumeMounts:
            - name: data
              mountPath: /usr/share/nginx/html
      volumes:
        - name: content
          configMap:
            name: arena-store-content
            items:
              - key: index.htlm
                path: index.html
        - name: data
          persistentVolumeClaim:
            claimName: arena-store-data
