apiVersion: v1
kind: Service
metadata:
  name: arena-store
  namespace: incident-arena-04
spec:
  clusterIP: None
  selector:
    app: arena-storage
  ports:
    - name: http
      port: 80
      targetPort: http
