apiVersion: v1
kind: Pod
metadata:
  name: arena-client
  namespace: incident-arena-03-client
  labels:
    app: arena-client
spec:
  containers:
    - name: curl
      image: curlimages/curl:8.12.1
      command:
        - sh
        - -c
        - sleep 3600
