apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: arena-api-ingress
  namespace: incident-arena-07-app
spec:
  podSelector:
    matchLabels:
      app: arena-api
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {}
    - from:
        - namespaceSelector:
            matchLabels:
              arena-access: client
      ports:
        - protocol: TCP
          port: 80
